'use strict';
module.exports = [
    { commands: ['json', 'jsonformat', 'prettyjson'], description: 'Format JSON', permission: 'public', run: async (s, m, a, c) => { try { const obj = JSON.parse(a.join(' ')); c.reply('```\n' + JSON.stringify(obj, null, 2) + '\n```'); } catch { c.reply('❌ Invalid JSON'); } }},
    { commands: ['urlencode', 'encodeurl'], description: 'URL encode', permission: 'public', run: async (s, m, a, c) => { const t = a.join(' '); if (!t) return c.reply('Usage: .urlencode <text>'); c.reply(encodeURIComponent(t)); }},
    { commands: ['urldecode', 'decodeurl'], description: 'URL decode', permission: 'public', run: async (s, m, a, c) => { const t = a.join(' '); if (!t) return c.reply('Usage: .urldecode <encoded>'); try { c.reply(decodeURIComponent(t)); } catch { c.reply('❌ Invalid encoded string'); } }},
    { commands: ['hash', 'md5', 'sha256'], description: 'Hash text', permission: 'public', run: async (s, m, a, c) => { const crypto = require('crypto'); const t = a.join(' '); if (!t) return c.reply('Usage: .hash <text>'); c.reply(`🔐 *Hash Results*\n\nMD5: ${crypto.createHash('md5').update(t).digest('hex')}\nSHA1: ${crypto.createHash('sha1').update(t).digest('hex')}\nSHA256: ${crypto.createHash('sha256').update(t).digest('hex')}`); }},
    { commands: ['timestamp', 'epoch', 'unixtime'], description: 'Unix timestamp', permission: 'public', run: async (s, m, a, c) => { const ts = parseInt(a[0]); if (ts) { const d = new Date(ts * (ts > 1e12 ? 1 : 1000)); c.reply(`⏱️ *Timestamp*\n\n${ts} → ${d.toISOString()}\n${d.toLocaleString()}`); } else { const now = Date.now(); c.reply(`⏱️ *Current Timestamp*\n\nSeconds: ${Math.floor(now/1000)}\nMilliseconds: ${now}\nISO: ${new Date().toISOString()}`); } }},
    { commands: ['regex', 'testregex'], description: 'Test regex pattern', permission: 'public', run: async (s, m, a, c) => { const pattern = a[0]; const text = a.slice(1).join(' '); if (!pattern || !text) return c.reply('Usage: .regex <pattern> <text>'); try { const re = new RegExp(pattern, 'g'); const matches = text.match(re); c.reply(`🔍 *Regex Test*\n\nPattern: /${pattern}/g\nText: ${text}\nMatches: ${matches ? matches.join(', ') : 'None'}\nCount: ${matches?.length || 0}`); } catch (e) { c.reply(`❌ Invalid regex: ${e.message}`); } }},
    { commands: ['color2', 'colorinfo'], description: 'Color information', permission: 'public', run: async (s, m, a, c) => { const colors = {red:{hex:'#FF0000',rgb:'255,0,0'},blue:{hex:'#0000FF',rgb:'0,0,255'},green:{hex:'#00FF00',rgb:'0,255,0'},yellow:{hex:'#FFFF00',rgb:'255,255,0'},purple:{hex:'#800080',rgb:'128,0,128'},orange:{hex:'#FFA500',rgb:'255,165,0'},pink:{hex:'#FFC0CB',rgb:'255,192,203'},black:{hex:'#000000',rgb:'0,0,0'},white:{hex:'#FFFFFF',rgb:'255,255,255'},cyan:{hex:'#00FFFF',rgb:'0,255,255'},magenta:{hex:'#FF00FF',rgb:'255,0,255'},brown:{hex:'#A52A2A',rgb:'165,42,42'},gray:{hex:'#808080',rgb:'128,128,128'},gold:{hex:'#FFD700',rgb:'255,215,0'},silver:{hex:'#C0C0C0',rgb:'192,192,192'},navy:{hex:'#000080',rgb:'0,0,128'},teal:{hex:'#008080',rgb:'0,128,128'},coral:{hex:'#FF7F50',rgb:'255,127,80'},salmon:{hex:'#FA8072',rgb:'250,128,114'},lime:{hex:'#00FF00',rgb:'0,255,0'}}; const q = (a[0]||'').toLowerCase(); const col = colors[q]; if (!col) return c.reply('Usage: .color2 <name>\nColors: ' + Object.keys(colors).join(', ')); c.reply(`🎨 *${q.charAt(0).toUpperCase()+q.slice(1)}*\n\nHEX: ${col.hex}\nRGB: rgb(${col.rgb})`); }},
    { commands: ['httpcode', 'statuscode', 'http'], description: 'HTTP status codes', permission: 'public', run: async (s, m, a, c) => { const codes = {200:'OK',201:'Created',204:'No Content',301:'Moved Permanently',302:'Found',304:'Not Modified',400:'Bad Request',401:'Unauthorized',403:'Forbidden',404:'Not Found',405:'Method Not Allowed',408:'Request Timeout',429:'Too Many Requests',500:'Internal Server Error',502:'Bad Gateway',503:'Service Unavailable',504:'Gateway Timeout'}; const code = a[0]; if (!code) return c.reply('Usage: .http <code>\nExample: .http 404'); c.reply(`🌐 *HTTP ${code}*\n\n${codes[code] || 'Unknown status code'}`); }},
    { commands: ['ascii2', 'charcode'], description: 'ASCII character codes', permission: 'public', run: async (s, m, a, c) => { const t = a.join(' '); if (!t) return c.reply('Usage: .ascii2 <text>'); c.reply(`📊 *ASCII Codes*\n\n${t.split('').map(ch => `'${ch}' = ${ch.charCodeAt(0)}`).join('\n')}`); }},
    { commands: ['ipinfo', 'iplookup'], description: 'IP address info', permission: 'public', run: async (s, m, a, c) => { const ip = a[0]; if (!ip) return c.reply('Usage: .ipinfo <ip_address>'); try { const axios = require('axios'); const res = await axios.get(`http://ip-api.com/json/${ip}`, {timeout:5000}); const d = res.data; if (d.status === 'fail') return c.reply(`❌ ${d.message}`); c.reply(`🌐 *IP Info: ${ip}*\n\nCountry: ${d.country}\nRegion: ${d.regionName}\nCity: ${d.city}\nISP: ${d.isp}\nOrg: ${d.org}\nTimezone: ${d.timezone}\nLat: ${d.lat}\nLon: ${d.lon}`); } catch { c.reply('❌ Could not look up IP'); } }},
    { commands: ['useragent', 'ua'], description: 'Random user agent', permission: 'public', run: async (s, m, a, c) => { const uas = ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0','Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/605.1.15 Safari/17.0','Mozilla/5.0 (X11; Linux x86_64) Gecko/20100101 Firefox/120.0','Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15','Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15']; c.reply(`🌐 *Random User Agent*\n\n\`${uas[Math.floor(Math.random()*uas.length)]}\``); }},
    { commands: ['wordcount', 'wc'], description: 'Detailed word count', permission: 'public', run: async (s, m, a, c) => { const t = a.join(' '); if (!t) return c.reply('Usage: .wc <text>'); const words = t.split(/\s+/).filter(Boolean); const sentences = t.split(/[.!?]+/).filter(Boolean); const vowels = (t.match(/[aeiou]/gi) || []).length; c.reply(`📊 *Text Analysis*\n\nCharacters: ${t.length}\nWords: ${words.length}\nSentences: ${sentences.length}\nVowels: ${vowels}\nConsonants: ${(t.match(/[bcdfghjklmnpqrstvwxyz]/gi)||[]).length}\nAvg word length: ${(t.replace(/\s/g,'').length / words.length).toFixed(1)}`); }},
    { commands: ['password2', 'passgen', 'genpass'], description: 'Advanced password generator', permission: 'public', run: async (s, m, a, c) => { const len = Math.min(parseInt(a[0]) || 16, 128); const type = (a[1]||'mixed').toLowerCase(); let chars; if (type === 'numbers' || type === 'num') chars = '0123456789'; else if (type === 'alpha') chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'; else if (type === 'hex') chars = '0123456789ABCDEF'; else chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-='; let pass = ''; for (let i = 0; i < len; i++) pass += chars[Math.floor(Math.random()*chars.length)]; c.reply(`🔐 *Password*\n\nLength: ${len}\nType: ${type}\n\n\`${pass}\`\n\nStrength: ${'🟩'.repeat(Math.min(Math.floor(len/4),5))}${'⬜'.repeat(5-Math.min(Math.floor(len/4),5))}`); }},
    { commands: ['cron', 'cronhelp'], description: 'Cron expression helper', permission: 'public', run: async (s, m, a, c) => { c.reply(`⏰ *Cron Expression Guide*\n\n\`* * * * *\`\n│ │ │ │ │\n│ │ │ │ └─ Day of Week (0-7)\n│ │ │ └── Month (1-12)\n│ │ └─── Day of Month (1-31)\n│ └──── Hour (0-23)\n└───── Minute (0-59)\n\n*Examples:*\n\`0 */2 * * *\` = Every 2 hours\n\`0 9 * * 1-5\` = 9 AM weekdays\n\`*/5 * * * *\` = Every 5 minutes\n\`0 0 * * 0\` = Midnight Sunday`); }},
    { commands: ['chmod', 'permissions'], description: 'Unix permissions calculator', permission: 'public', run: async (s, m, a, c) => { const n = parseInt(a[0]); if (isNaN(n) || n < 0 || n > 777) return c.reply('Usage: .chmod <number>\nExample: .chmod 755'); const perms = n.toString().split('').map(d => { const v = parseInt(d); return `${v&4?'r':'-'}${v&2?'w':'-'}${v&1?'x':'-'}`; }); c.reply(`📁 *Permissions: ${n}*\n\nOwner: ${perms[0] || '---'}\nGroup: ${perms[1] || '---'}\nOther: ${perms[2] || '---'}\n\nFull: ${perms.join('')}`); }},
];
