'use strict';
const state = {};
module.exports = [
    { commands: ['emojiguess', 'guessemoji', 'eg'], description: 'Guess the emoji meaning', permission: 'public', run: async (s, m, a, c) => { const puzzles = [{emoji:'🎬🦁👑',answer:'The Lion King'},{emoji:'🕷️🧑',answer:'Spider-Man'},{emoji:'⭐⚔️',answer:'Star Wars'},{emoji:'🧊🏔️❄️',answer:'Frozen'},{emoji:'🦇🧑',answer:'Batman'},{emoji:'🧙‍♂️💍',answer:'Lord of the Rings'},{emoji:'👻👻👻',answer:'Ghostbusters'},{emoji:'🚢❄️💑',answer:'Titanic'},{emoji:'🏠👆',answer:'Up'},{emoji:'🧸🍯',answer:'Winnie the Pooh'},{emoji:'🐠🔍',answer:'Finding Nemo'},{emoji:'🤖🌱',answer:'Wall-E'},{emoji:'👸❄️⛄',answer:'Frozen'},{emoji:'🦁🐗🐾',answer:'The Lion King'},{emoji:'🧛🩸',answer:'Dracula'}]; const p = puzzles[Math.floor(Math.random()*puzzles.length)]; state[c.from+'_eg'] = p.answer; c.reply(`🎬 *Guess the Movie!*\n\n${p.emoji}\n\nReply with .emojianswer <your guess>`); }},
    { commands: ['emojianswer', 'ea'], description: 'Answer emoji guess', permission: 'public', run: async (s, m, a, c) => { const key = c.from+'_eg'; if (!state[key]) return c.reply('Start a game with .emojiguess first!'); const answer = state[key]; const guess = a.join(' ').toLowerCase(); if (answer.toLowerCase().includes(guess) || guess.includes(answer.toLowerCase())) { delete state[key]; c.reply(`✅ *Correct!* It's "${answer}"!`); } else { c.reply(`❌ Wrong! Try again or .emojiguess for a new one.`); } }},
    { commands: ['flagquiz', 'guessflag', 'fq'], description: 'Guess the country from flag', permission: 'public', run: async (s, m, a, c) => { const flags = [{flag:'🇰🇪',country:'Kenya'},{flag:'🇺🇸',country:'USA'},{flag:'🇬🇧',country:'United Kingdom'},{flag:'🇯🇵',country:'Japan'},{flag:'🇧🇷',country:'Brazil'},{flag:'🇫🇷',country:'France'},{flag:'🇩🇪',country:'Germany'},{flag:'🇮🇹',country:'Italy'},{flag:'🇨🇳',country:'China'},{flag:'🇮🇳',country:'India'},{flag:'🇳🇬',country:'Nigeria'},{flag:'🇿🇦',country:'South Africa'},{flag:'🇪🇬',country:'Egypt'},{flag:'🇦🇺',country:'Australia'},{flag:'🇨🇦',country:'Canada'},{flag:'🇲🇽',country:'Mexico'},{flag:'🇪🇸',country:'Spain'},{flag:'🇹🇷',country:'Turkey'},{flag:'🇰🇷',country:'South Korea'},{flag:'🇷🇺',country:'Russia'}]; const f = flags[Math.floor(Math.random()*flags.length)]; state[c.from+'_fq'] = f.country; c.reply(`🏳️ *Guess the Country!*\n\n${f.flag} ${f.flag} ${f.flag}\n\nReply with .flaganswer <country>`); }},
    { commands: ['flaganswer', 'fa'], description: 'Answer flag quiz', permission: 'public', run: async (s, m, a, c) => { const key = c.from+'_fq'; if (!state[key]) return c.reply('Start with .flagquiz first!'); const answer = state[key]; const guess = a.join(' ').toLowerCase(); if (answer.toLowerCase() === guess || answer.toLowerCase().includes(guess)) { delete state[key]; c.reply(`✅ *Correct!* It's ${answer}!`); } else { c.reply('❌ Wrong! Try again.'); } }},
    { commands: ['mathquiz', 'mq', 'quickmath'], description: 'Quick math quiz', permission: 'public', run: async (s, m, a, c) => { const ops = ['+','-','×']; const op = ops[Math.floor(Math.random()*3)]; let a1, b1, answer; if (op === '+') { a1 = Math.floor(Math.random()*100); b1 = Math.floor(Math.random()*100); answer = a1+b1; } else if (op === '-') { a1 = Math.floor(Math.random()*100)+50; b1 = Math.floor(Math.random()*50); answer = a1-b1; } else { a1 = Math.floor(Math.random()*12)+1; b1 = Math.floor(Math.random()*12)+1; answer = a1*b1; } state[c.from+'_mq'] = answer; c.reply(`🔢 *Quick Math!*\n\n${a1} ${op} ${b1} = ?\n\nReply with .mathanswer <number>`); }},
    { commands: ['mathanswer', 'ma'], description: 'Answer math quiz', permission: 'public', run: async (s, m, a, c) => { const key = c.from+'_mq'; if (!state[key] && state[key] !== 0) return c.reply('Start with .mathquiz first!'); if (parseInt(a[0]) === state[key]) { delete state[key]; c.reply('✅ *Correct!* 🎉'); } else { c.reply(`❌ Wrong! The answer was *${state[key]}*`); delete state[key]; } }},
    { commands: ['capitalquiz', 'cq', 'guesscapital'], description: 'Guess the capital city', permission: 'public', run: async (s, m, a, c) => { const data = [{country:'Kenya',capital:'Nairobi'},{country:'Japan',capital:'Tokyo'},{country:'France',capital:'Paris'},{country:'Brazil',capital:'Brasília'},{country:'Australia',capital:'Canberra'},{country:'Egypt',capital:'Cairo'},{country:'Germany',capital:'Berlin'},{country:'Italy',capital:'Rome'},{country:'Canada',capital:'Ottawa'},{country:'India',capital:'New Delhi'},{country:'Nigeria',capital:'Abuja'},{country:'South Africa',capital:'Pretoria'},{country:'Tanzania',capital:'Dodoma'},{country:'Uganda',capital:'Kampala'},{country:'Ethiopia',capital:'Addis Ababa'},{country:'Spain',capital:'Madrid'},{country:'China',capital:'Beijing'},{country:'Russia',capital:'Moscow'},{country:'Turkey',capital:'Ankara'},{country:'Thailand',capital:'Bangkok'}]; const q = data[Math.floor(Math.random()*data.length)]; state[c.from+'_cq'] = q.capital; c.reply(`🏛️ *Guess the Capital!*\n\nWhat is the capital of *${q.country}*?\n\nReply with .capitalanswer <city>`); }},
    { commands: ['capitalanswer', 'ca'], description: 'Answer capital quiz', permission: 'public', run: async (s, m, a, c) => { const key = c.from+'_cq'; if (!state[key]) return c.reply('Start with .capitalquiz first!'); const answer = state[key]; const guess = a.join(' ').toLowerCase(); if (answer.toLowerCase() === guess || answer.toLowerCase().includes(guess)) { delete state[key]; c.reply(`✅ *Correct!* It's ${answer}!`); } else { c.reply(`❌ Wrong! The answer was *${answer}*`); delete state[key]; } }},
    { commands: ['unscramble2', 'wordchallenge'], description: 'Unscramble challenge', permission: 'public', run: async (s, m, a, c) => { const words = ['elephant','chocolate','sunshine','computer','beautiful','adventure','knowledge','mountain','dinosaur','universe','butterfly','waterfall','pineapple','telephone','chemistry','geography','astronomy','education','democracy','evolution']; const word = words[Math.floor(Math.random()*words.length)]; const scrambled = word.split('').sort(()=>Math.random()-0.5).join(''); state[c.from+'_us'] = word; c.reply(`🔤 *Unscramble!*\n\n*${scrambled.toUpperCase()}*\n\nHint: ${word.length} letters\nCategory: General Knowledge\n\nReply with .unscrambleanswer <word>`); }},
    { commands: ['unscrambleanswer', 'usa'], description: 'Answer unscramble', permission: 'public', run: async (s, m, a, c) => { const key = c.from+'_us'; if (!state[key]) return c.reply('Start with .unscramble2 first!'); if (a[0]?.toLowerCase() === state[key]) { delete state[key]; c.reply('✅ *Correct!* 🎉'); } else { c.reply('❌ Wrong! Try again.'); } }},
    { commands: ['typerace', 'typing2'], description: 'Typing race challenge', permission: 'public', run: async (s, m, a, c) => { const phrases = ['The quick brown fox jumps over the lazy dog','Practice makes perfect and nobody is perfect','Life is like a box of chocolates you never know what you get','Actions speak louder than words so show dont tell','Every cloud has a silver lining keep looking up']; const phrase = phrases[Math.floor(Math.random()*phrases.length)]; state[c.from+'_tr'] = {phrase, time: Date.now()}; c.reply(`⌨️ *Typing Race!*\n\nType this exactly:\n\n*${phrase}*\n\nReply with .typecheck <your text>`); }},
    { commands: ['typecheck', 'tc'], description: 'Check typing race', permission: 'public', run: async (s, m, a, c) => { const key = c.from+'_tr'; if (!state[key]) return c.reply('Start with .typerace first!'); const elapsed = (Date.now() - state[key].time) / 1000; const typed = a.join(' '); const correct = state[key].phrase; delete state[key]; const accuracy = Math.round((typed.split('').filter((ch,i) => ch === correct[i]).length / correct.length) * 100); const wpm = Math.round((correct.split(' ').length / elapsed) * 60); c.reply(`⌨️ *Typing Results*\n\nTime: ${elapsed.toFixed(1)}s\nWPM: ~${wpm}\nAccuracy: ${accuracy}%\n\n${accuracy === 100 ? '🏆 Perfect!' : accuracy > 80 ? '👍 Good job!' : '📝 Keep practicing!'}`); }},
];
