'use strict';
module.exports = [
    { commands: ['antiban', 'safemode', 'antibansettings'], description: 'Anti-ban safety settings', permission: 'owner', run: async (s, m, a, c) => { c.reply(`🛡️ *Anti-Ban Safety Features*\n\n✅ Rate limiting: Active (max 30 msgs/min)\n✅ Message jitter: Active (100-500ms delay)\n✅ Anti-spam protection: Available\n✅ Anti-flood protection: Available\n\n*Tips to stay safe:*\n• Don't send bulk messages\n• Don't spam groups\n• Don't use the bot in too many groups\n• Keep auto-features limited\n• Don't forward too many messages\n\nUse .settings to configure`); }},
    { commands: ['settings', 'botsettings', 'config2'], description: 'View bot settings', permission: 'owner', run: async (s, m, a, c) => { const config = require('../config'); c.reply(`⚙️ *Bot Settings*\n\nBot Name: ${config.BOT_NAME}\nPrefix: ${config.PREFIX}\nMode: ${config.MODE}\nAnti-Delete (Group): ${config.ANTIDELETE_GROUP}\nAnti-Delete (Private): ${config.ANTIDELETE_PRIVATE}\nAuto Status Seen: ${config.AUTO_STATUS_SEEN}\nAuto Status React: ${config.AUTO_STATUS_REACT}\nAlways Online: ${config.ALWAYS_ONLINE}\nAuto Typing: ${config.AUTO_TYPING}\nAnti-Link: ${config.ANTILINK}\nAnti-VV: ${config.ANTIVV}\nDebug: ${config.DEBUG}`); }},
    { commands: ['setprefix', 'prefix2'], description: 'Change command prefix', permission: 'owner', run: async (s, m, a, c) => { const newPrefix = a[0]; if (!newPrefix) return c.reply('Usage: .setprefix <new_prefix>'); process.env.PREFIX = newPrefix; c.reply(`✅ Prefix changed to: *${newPrefix}*\n\n_Note: This change is temporary until restart._`); }},
    { commands: ['setmode', 'mode2'], description: 'Change bot mode', permission: 'owner', run: async (s, m, a, c) => { const mode = (a[0]||'').toLowerCase(); if (!['public','private','both'].includes(mode)) return c.reply('Usage: .setmode public/private/both'); process.env.MODE = mode; c.reply(`✅ Bot mode changed to: *${mode}*`); }},
    { commands: ['block', 'blockuser'], description: 'Block a number', permission: 'owner', run: async (s, m, a, c) => { const num = a[0]?.replace(/[^0-9]/g, ''); if (!num) return c.reply('Usage: .block <number>'); try { await s.updateBlockStatus(`${num}@s.whatsapp.net`, 'block'); c.reply(`✅ Blocked: ${num}`); } catch (e) { c.reply(`❌ Failed: ${e.message}`); } }},
    { commands: ['unblock', 'unblockuser'], description: 'Unblock a number', permission: 'owner', run: async (s, m, a, c) => { const num = a[0]?.replace(/[^0-9]/g, ''); if (!num) return c.reply('Usage: .unblock <number>'); try { await s.updateBlockStatus(`${num}@s.whatsapp.net`, 'unblock'); c.reply(`✅ Unblocked: ${num}`); } catch (e) { c.reply(`❌ Failed: ${e.message}`); } }},
    { commands: ['setbio', 'bio', 'updatebio'], description: 'Update bot bio/status', permission: 'owner', run: async (s, m, a, c) => { const bio = a.join(' '); if (!bio) return c.reply('Usage: .setbio <new bio text>'); try { await s.updateProfileStatus(bio); c.reply(`✅ Bio updated to: "${bio}"`); } catch (e) { c.reply(`❌ Failed: ${e.message}`); } }},
    { commands: ['setname', 'botname'], description: 'Update bot display name', permission: 'owner', run: async (s, m, a, c) => { const name = a.join(' '); if (!name) return c.reply('Usage: .setname <new name>'); try { await s.updateProfileName(name); c.reply(`✅ Name updated to: "${name}"`); } catch (e) { c.reply(`❌ Failed: ${e.message}`); } }},
    { commands: ['clearcache', 'cleartmp', 'cleanup'], description: 'Clear temporary files', permission: 'owner', run: async (s, m, a, c) => { const fs = require('fs'); const path = require('path'); const tmpDir = path.join(__dirname, '..', 'temp'); try { if (fs.existsSync(tmpDir)) { const files = fs.readdirSync(tmpDir); for (const f of files) fs.unlinkSync(path.join(tmpDir, f)); c.reply(`✅ Cleared ${files.length} temp files`); } else { c.reply('✅ No temp directory found'); } } catch (e) { c.reply(`❌ Error: ${e.message}`); } }},
    { commands: ['restart2', 'reboot'], description: 'Restart bot', permission: 'owner', run: async (s, m, a, c) => { await c.reply('♻️ Restarting bot in 3 seconds...'); setTimeout(() => process.exit(0), 3000); }},
    { commands: ['broadcast2', 'massbc'], description: 'Broadcast to all groups', permission: 'owner', group: false, run: async (s, m, a, c) => { const text = a.join(' '); if (!text) return c.reply('Usage: .broadcast2 <message>'); c.reply('📢 Broadcast feature available. Use .broadcast for full broadcast.'); }},
    { commands: ['leave', 'leavegroup', 'quit'], description: 'Leave a group', permission: 'owner', run: async (s, m, a, c) => { if (!c.isGroup) return c.reply('This command is for groups only'); await c.reply('👋 Goodbye everyone!'); try { await s.groupLeave(c.jid); } catch (e) { c.reply(`❌ Failed to leave: ${e.message}`); } }},
    { commands: ['join', 'joingroup'], description: 'Join a group by link', permission: 'owner', run: async (s, m, a, c) => { const link = a[0]; if (!link) return c.reply('Usage: .join <group_invite_link>'); try { const code = link.split('/').pop(); await s.groupAcceptInvite(code); c.reply('✅ Joined the group!'); } catch (e) { c.reply(`❌ Failed: ${e.message}`); } }},
    { commands: ['antilink2', 'toggleantilink'], description: 'Toggle anti-link per group', permission: 'admin', group: true, private: false, run: async (s, m, a, c) => { if (!global.antilinkGroups) global.antilinkGroups = new Set(); if (global.antilinkGroups.has(c.jid)) { global.antilinkGroups.delete(c.jid); c.reply('✅ Anti-link disabled for this group'); } else { global.antilinkGroups.add(c.jid); c.reply('✅ Anti-link enabled for this group'); } }},
    { commands: ['antibadword', 'badword', 'antibad'], description: 'Toggle anti-bad words', permission: 'admin', group: true, private: false, run: async (s, m, a, c) => { if (!global.antibadGroups) global.antibadGroups = new Set(); if (global.antibadGroups.has(c.jid)) { global.antibadGroups.delete(c.jid); c.reply('✅ Anti-bad words disabled'); } else { global.antibadGroups.add(c.jid); c.reply('✅ Anti-bad words enabled'); } }},
    { commands: ['disappear', 'ephemeral'], description: 'Toggle disappearing messages', permission: 'admin', group: true, private: false, run: async (s, m, a, c) => { const duration = parseInt(a[0]) || 86400; try { await s.sendMessage(c.jid, { disappearingMessagesInChat: duration }); c.reply(`✅ Disappearing messages set to ${duration}s`); } catch (e) { c.reply(`❌ Failed: ${e.message}`); } }},
];
