'use strict';
module.exports = [
    { commands: ['tagall', 'everyone', 'all'], description: 'Tag all group members', permission: 'admin', group: true, private: false, run: async (s, m, a, c) => { if (!c.groupMetadata?.participants) return c.reply('Could not get group members'); const mentions = c.groupMetadata.participants.map(p => p.id); const msg = a.join(' ') || 'Attention everyone!'; const text = `📢 *${msg}*\n\n${mentions.map(jid => `@${jid.split('@')[0]}`).join('\n')}`; await s.sendMessage(c.jid, { text, mentions }, { quoted: m }); }},
    { commands: ['hidetag', 'htag'], description: 'Send message tagging all silently', permission: 'admin', group: true, private: false, run: async (s, m, a, c) => { if (!c.groupMetadata?.participants) return c.reply('Could not get group members'); const mentions = c.groupMetadata.participants.map(p => p.id); const text = a.join(' ') || '🔔'; await s.sendMessage(c.jid, { text, mentions }, { quoted: m }); }},
    { commands: ['admins', 'listadmins'], description: 'List group admins', permission: 'public', group: true, private: false, run: async (s, m, a, c) => { if (!c.groupMetadata?.participants) return c.reply('Could not get group info'); const admins = c.groupMetadata.participants.filter(p => p.admin); const text = `👑 *Group Admins*\n\n${admins.map(a => `• @${a.id.split('@')[0]} (${a.admin})`).join('\n')}`; await s.sendMessage(c.jid, { text, mentions: admins.map(a => a.id) }, { quoted: m }); }},
    { commands: ['groupinfo', 'ginfo', 'gi'], description: 'Group information', permission: 'public', group: true, private: false, run: async (s, m, a, c) => { const gm = c.groupMetadata; if (!gm) return c.reply('Could not get group info'); const admins = gm.participants?.filter(p => p.admin).length || 0; c.reply(`👥 *Group Information*\n\nName: ${gm.subject}\nMembers: ${gm.participants?.length || 0}\nAdmins: ${admins}\nDescription: ${gm.desc || 'None'}\nCreated: ${gm.creation ? new Date(gm.creation * 1000).toLocaleDateString() : 'Unknown'}`); }},
    { commands: ['mute', 'muteuser'], description: 'Mute a user in group', permission: 'admin', group: true, private: false, botAdmin: true, run: async (s, m, a, c) => { const mentioned = c.mentionedJid?.[0] || (m.message?.extendedTextMessage?.contextInfo?.participant); if (!mentioned) return c.reply('Tag someone to mute'); if (!global.groupMutedMembers) global.groupMutedMembers = new Map(); if (!global.groupMutedMembers.has(c.jid)) global.groupMutedMembers.set(c.jid, new Set()); global.groupMutedMembers.get(c.jid).add(mentioned); await s.sendMessage(c.jid, { text: `🔇 @${mentioned.split('@')[0]} has been muted.`, mentions: [mentioned] }, { quoted: m }); }},
    { commands: ['unmute', 'unmuteuser'], description: 'Unmute a user in group', permission: 'admin', group: true, private: false, run: async (s, m, a, c) => { const mentioned = c.mentionedJid?.[0] || (m.message?.extendedTextMessage?.contextInfo?.participant); if (!mentioned) return c.reply('Tag someone to unmute'); global.groupMutedMembers?.get(c.jid)?.delete(mentioned); await s.sendMessage(c.jid, { text: `🔊 @${mentioned.split('@')[0]} has been unmuted.`, mentions: [mentioned] }, { quoted: m }); }},
    { commands: ['warn', 'warning'], description: 'Warn a user', permission: 'admin', group: true, private: false, run: async (s, m, a, c) => { const mentioned = c.mentionedJid?.[0]; if (!mentioned) return c.reply('Tag someone to warn'); if (!global.warnings) global.warnings = {}; const key = `${c.jid}-${mentioned}`; global.warnings[key] = (global.warnings[key] || 0) + 1; const warns = global.warnings[key]; const reason = a.slice(1).join(' ') || 'No reason specified'; await s.sendMessage(c.jid, { text: `⚠️ *Warning ${warns}/3*\n\n@${mentioned.split('@')[0]} has been warned.\nReason: ${reason}${warns >= 3 ? '\n\n🚫 3 warnings reached! Admin action needed.' : ''}`, mentions: [mentioned] }, { quoted: m }); if (warns >= 3) { try { await s.groupParticipantsUpdate(c.jid, [mentioned], 'remove'); } catch {} } }},
    { commands: ['resetwarn', 'clearwarn'], description: 'Reset warnings', permission: 'admin', group: true, private: false, run: async (s, m, a, c) => { const mentioned = c.mentionedJid?.[0]; if (!mentioned) return c.reply('Tag someone'); const key = `${c.jid}-${mentioned}`; if (global.warnings) delete global.warnings[key]; await s.sendMessage(c.jid, { text: `✅ Warnings cleared for @${mentioned.split('@')[0]}`, mentions: [mentioned] }, { quoted: m }); }},
    { commands: ['antiflood', 'flood'], description: 'Toggle anti-flood', permission: 'admin', group: true, private: false, run: async (s, m, a, c) => { if (!global.antifloodSettings) global.antifloodSettings = new Map(); const current = global.antifloodSettings.get(c.jid); if (current?.enabled) { global.antifloodSettings.delete(c.jid); c.reply('✅ Anti-flood disabled'); } else { global.antifloodSettings.set(c.jid, { enabled: true, maxMsg: parseInt(a[0]) || 10, timeWindow: 10000 }); c.reply(`✅ Anti-flood enabled (${parseInt(a[0]) || 10} msgs per 10s)`); } }},
    { commands: ['antispam', 'spam'], description: 'Toggle anti-spam', permission: 'admin', group: true, private: false, run: async (s, m, a, c) => { if (!global.antispamGroups) global.antispamGroups = new Set(); if (global.antispamGroups.has(c.jid)) { global.antispamGroups.delete(c.jid); c.reply('✅ Anti-spam disabled'); } else { global.antispamGroups.add(c.jid); c.reply('✅ Anti-spam enabled'); } }},
    { commands: ['report', 'reportuser'], description: 'Report a user to admins', permission: 'public', group: true, private: false, run: async (s, m, a, c) => { const mentioned = c.mentionedJid?.[0]; if (!mentioned) return c.reply('Tag the user to report'); const reason = a.slice(1).join(' ') || 'No reason given'; const admins = c.groupMetadata?.participants?.filter(p => p.admin).map(p => p.id) || []; const text = `🚨 *User Report*\n\nReported: @${mentioned.split('@')[0]}\nBy: @${c.from.split('@')[0]}\nReason: ${reason}`; await s.sendMessage(c.jid, { text, mentions: [mentioned, c.from, ...admins] }, { quoted: m }); }},
    { commands: ['rules', 'grouprules'], description: 'Set/view group rules', permission: 'public', group: true, private: false, run: async (s, m, a, c) => { if (!global.groupRules) global.groupRules = {}; if (a[0] === 'set' && (c.isAdmin || c.isOwner)) { const rules = a.slice(1).join(' '); if (!rules) return c.reply('Usage: .rules set <rules text>'); global.groupRules[c.jid] = rules; return c.reply('✅ Group rules updated!'); } c.reply(`📜 *Group Rules*\n\n${global.groupRules[c.jid] || 'No rules set. Admins can set with: .rules set <rules>'}`); }},
    { commands: ['afkcheck', 'whoafk'], description: 'Check who is AFK', permission: 'public', run: async (s, m, a, c) => { c.reply('📋 *AFK Status*\n\nUse .afk <reason> to set yourself as AFK\nUse .back to return from AFK'); }},
    { commands: ['vcard', 'contact', 'sharecontact'], description: 'Share contact card', permission: 'public', run: async (s, m, a, c) => { const number = a[0]?.replace(/[^0-9]/g, ''); const name = a.slice(1).join(' ') || 'Contact'; if (!number) return c.reply('Usage: .vcard <number> <name>'); const vcard = `BEGIN:VCARD\nVERSION:3.0\nFN:${name}\nTEL;type=CELL;type=VOICE;waid=${number}:+${number}\nEND:VCARD`; await s.sendMessage(c.jid, { contacts: { displayName: name, contacts: [{ vcard }] } }, { quoted: m }); }},
    { commands: ['listonline', 'online'], description: 'Request online presence', permission: 'admin', group: true, private: false, run: async (s, m, a, c) => { c.reply('👥 *Online Check*\n\nWhatsApp does not allow bots to reliably detect online status of all members. Try tagging members directly.'); }},
];
