'use strict';
const os = require('os');
module.exports = [
    { commands: ['date', 'today'], description: 'Current date and time', permission: 'public', run: async (s, m, a, c) => { const now = new Date(); const zones = {EAT:'Africa/Nairobi',EST:'America/New_York',PST:'America/Los_Angeles',GMT:'Europe/London',IST:'Asia/Kolkata',JST:'Asia/Tokyo'}; let tz = 'Africa/Nairobi', label = 'EAT'; if (a[0]) { const up = a[0].toUpperCase(); if (zones[up]) { tz = zones[up]; label = up; } } c.reply(`📅 *Date & Time (${label})*\n\n${now.toLocaleString('en-US',{timeZone:tz,weekday:'long',year:'numeric',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true})}`); }},
    { commands: ['calendar', 'cal'], description: 'Show calendar', permission: 'public', run: async (s, m, a, c) => { const now = new Date(); const month = parseInt(a[0]) || now.getMonth()+1; const year = parseInt(a[1]) || now.getFullYear(); const firstDay = new Date(year,month-1,1).getDay(); const daysInMonth = new Date(year,month,0).getDate(); const monthName = new Date(year,month-1).toLocaleString('en',{month:'long'}); let cal = `📅 *${monthName} ${year}*\n\nSu Mo Tu We Th Fr Sa\n`; cal += '   '.repeat(firstDay); for (let d = 1; d <= daysInMonth; d++) { cal += d.toString().padStart(2,' ') + ' '; if ((firstDay+d)%7===0) cal += '\n'; } c.reply(cal); }},
    { commands: ['timer', 'countdown'], description: 'Set a timer', permission: 'public', run: async (s, m, a, c) => { const mins = parseInt(a[0]); if (!mins || mins < 1 || mins > 60) return c.reply('Usage: .timer <minutes 1-60>'); c.reply(`⏱️ Timer set for *${mins} minute(s)*!`); setTimeout(() => c.safeSend({text:`⏰ *Time's up!* ${mins} minute(s) have passed!`},{quoted:m}), mins*60*1000); }},
    { commands: ['stopwatch', 'sw'], description: 'Stopwatch', permission: 'public', run: async (s, m, a, c) => { if (!global.stopwatches) global.stopwatches = {}; const key = c.from; if (a[0] === 'stop' && global.stopwatches[key]) { const elapsed = Date.now() - global.stopwatches[key]; delete global.stopwatches[key]; const s = Math.floor(elapsed/1000); const ms = elapsed%1000; c.reply(`⏱️ *Stopwatch Stopped*\n\nTime: ${Math.floor(s/60)}m ${s%60}s ${ms}ms`); } else { global.stopwatches[key] = Date.now(); c.reply('⏱️ *Stopwatch Started!*\n\nStop with: .stopwatch stop'); } }},
    { commands: ['timezone', 'tz', 'worldclock'], description: 'World clock', permission: 'public', run: async (s, m, a, c) => { const zones = [['🇰🇪 Nairobi','Africa/Nairobi'],['🇬🇧 London','Europe/London'],['🇺🇸 New York','America/New_York'],['🇺🇸 LA','America/Los_Angeles'],['🇯🇵 Tokyo','Asia/Tokyo'],['🇮🇳 Mumbai','Asia/Kolkata'],['🇦🇺 Sydney','Australia/Sydney'],['🇦🇪 Dubai','Asia/Dubai'],['🇧🇷 São Paulo','America/Sao_Paulo'],['🇨🇳 Beijing','Asia/Shanghai']]; const lines = zones.map(([name,tz]) => `${name}: ${new Date().toLocaleTimeString('en-US',{timeZone:tz,hour:'2-digit',minute:'2-digit',hour12:true})}`); c.reply(`🌍 *World Clock*\n\n${lines.join('\n')}`); }},
    { commands: ['ip', 'myip', 'serverip'], description: 'Show server info', permission: 'public', run: async (s, m, a, c) => { const nets = os.networkInterfaces(); const ips = []; for (const name of Object.keys(nets)) for (const net of nets[name]) if (!net.internal && net.family === 'IPv4') ips.push(`${name}: ${net.address}`); c.reply(`🖥️ *Server Info*\n\nPlatform: ${os.platform()}\nArch: ${os.arch()}\nCPUs: ${os.cpus().length}\nMemory: ${(os.totalmem()/1e9).toFixed(1)}GB\nFree: ${(os.freemem()/1e9).toFixed(1)}GB\nUptime: ${Math.floor(os.uptime()/3600)}h`); }},
    { commands: ['qr', 'qrcode', 'makeqr'], description: 'Generate QR code text', permission: 'public', run: async (s, m, a, c) => { const text = a.join(' '); if (!text) return c.reply('Usage: .qr <text or URL>'); try { const qrcode = require('qrcode'); const buf = await qrcode.toBuffer(text, {width:300}); await s.sendMessage(c.jid, {image:buf, caption:`📱 QR Code for: ${text}`}, {quoted:m}); } catch { c.reply('❌ Failed to generate QR code'); } }},
    { commands: ['shorten', 'shorturl', 'tinyurl'], description: 'Shorten URL', permission: 'public', run: async (s, m, a, c) => { const url = a[0]; if (!url) return c.reply('Usage: .shorten <url>'); try { const axios = require('axios'); const res = await axios.get(`https://tinyurl.com/api-create.php?url=${encodeURIComponent(url)}`); c.reply(`🔗 *URL Shortened*\n\nOriginal: ${url}\nShort: ${res.data}`); } catch { c.reply('❌ Failed to shorten URL'); } }},
    { commands: ['choose', 'pick', 'decide'], description: 'Pick random option', permission: 'public', run: async (s, m, a, c) => { const opts = a.join(' ').split(/[,|\/]/); if (opts.length < 2) return c.reply('Usage: .choose option1, option2, option3'); const picked = opts[Math.floor(Math.random()*opts.length)].trim(); c.reply(`🎯 *Decision Maker*\n\nOptions: ${opts.map(o=>o.trim()).join(' | ')}\n\nI choose: *${picked}*`); }},
    { commands: ['poll2', 'quickpoll'], description: 'Quick text poll', permission: 'public', run: async (s, m, a, c) => { const parts = a.join(' ').split('|'); if (parts.length < 3) return c.reply('Usage: .poll2 Question | Option1 | Option2 | Option3'); const question = parts[0].trim(); const options = parts.slice(1).map((o,i) => `${i+1}. ${o.trim()}`); c.reply(`📊 *Poll*\n\n❓ ${question}\n\n${options.join('\n')}\n\n_Reply with the number of your choice!_`); }},
    { commands: ['note', 'notes', 'memo'], description: 'Save/view notes', permission: 'public', run: async (s, m, a, c) => { if (!global.notes) global.notes = {}; const key = c.from; if (!global.notes[key]) global.notes[key] = []; if (a[0] === 'list' || !a.length) { if (!global.notes[key].length) return c.reply('📝 No notes saved. Use: .note <text>'); return c.reply(`📝 *Your Notes*\n\n${global.notes[key].map((n,i)=>`${i+1}. ${n}`).join('\n')}\n\nDelete: .note del <number>\nClear: .note clear`); } if (a[0] === 'del') { const idx = parseInt(a[1])-1; if (isNaN(idx) || !global.notes[key][idx]) return c.reply('Invalid note number'); global.notes[key].splice(idx,1); return c.reply('✅ Note deleted'); } if (a[0] === 'clear') { global.notes[key] = []; return c.reply('✅ All notes cleared'); } global.notes[key].push(a.join(' ')); c.reply(`✅ Note saved! (${global.notes[key].length} total)`); }},
    { commands: ['todo', 'todolist', 'task'], description: 'Todo list', permission: 'public', run: async (s, m, a, c) => { if (!global.todos) global.todos = {}; const key = c.from; if (!global.todos[key]) global.todos[key] = []; if (!a.length || a[0] === 'list') { if (!global.todos[key].length) return c.reply('📋 Empty todo list. Use: .todo <task>'); return c.reply(`📋 *Todo List*\n\n${global.todos[key].map((t,i)=>`${t.done?'✅':'⬜'} ${i+1}. ${t.text}`).join('\n')}\n\nDone: .todo done <n>\nRemove: .todo rm <n>\nClear: .todo clear`); } if (a[0] === 'done') { const idx = parseInt(a[1])-1; if (global.todos[key][idx]) global.todos[key][idx].done = true; return c.reply('✅ Marked as done!'); } if (a[0] === 'rm') { const idx = parseInt(a[1])-1; if (global.todos[key][idx]) global.todos[key].splice(idx,1); return c.reply('✅ Removed!'); } if (a[0] === 'clear') { global.todos[key] = []; return c.reply('✅ Todo list cleared!'); } global.todos[key].push({text:a.join(' '),done:false}); c.reply(`✅ Added to todo list! (${global.todos[key].length} items)`); }},
    { commands: ['hashtag', 'tags', 'generatetags'], description: 'Generate hashtags', permission: 'public', run: async (s, m, a, c) => { const topic = a.join(' '); if (!topic) return c.reply('Usage: .hashtag <topic>'); const words = topic.toLowerCase().split(/\s+/); const tags = words.map(w => `#${w}`); const extras = words.flatMap(w => [`#${w}life`, `#${w}vibes`, `#best${w}`, `#${w}lovers`, `#${w}daily`]); const all = [...new Set([...tags, ...extras])].slice(0, 30); c.reply(`#️⃣ *Hashtag Generator*\n\nTopic: ${topic}\n\n${all.join(' ')}`); }},
    { commands: ['uuid', 'guid'], description: 'Generate UUID', permission: 'public', run: async (s, m, a, c) => { const { randomUUID } = require('crypto'); const count = Math.min(parseInt(a[0]) || 1, 10); const uuids = Array(count).fill(0).map(() => randomUUID()); c.reply(`🔑 *UUID Generator*\n\n${uuids.join('\n')}`); }},
    { commands: ['lorem', 'loremipsum'], description: 'Generate lorem ipsum', permission: 'public', run: async (s, m, a, c) => { const words = 'Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum'.split(' '); const count = Math.min(parseInt(a[0]) || 50, 500); const text = Array(count).fill(0).map(() => words[Math.floor(Math.random()*words.length)]).join(' '); c.reply(text[0].toUpperCase() + text.slice(1) + '.'); }},
    { commands: ['coin', 'flipcoin', 'coinflip'], description: 'Flip a coin', permission: 'public', run: async (s, m, a, c) => { const result = Math.random() < 0.5 ? 'Heads 🪙' : 'Tails 🪙'; c.reply(`🪙 *Coin Flip*\n\nResult: *${result}*`); }},
    { commands: ['dice', 'rolldice'], description: 'Roll dice', permission: 'public', run: async (s, m, a, c) => { const sides = parseInt(a[0]) || 6; const count = Math.min(parseInt(a[1]) || 1, 10); const rolls = Array(count).fill(0).map(() => Math.floor(Math.random()*sides)+1); c.reply(`🎲 *Dice Roll* (${count}x d${sides})\n\nResults: ${rolls.join(', ')}\nTotal: *${rolls.reduce((a,b)=>a+b,0)}*`); }},
    { commands: ['countdown2', 'daysto'], description: 'Days until date', permission: 'public', run: async (s, m, a, c) => { const d = new Date(a.join(' ')); if (isNaN(d.getTime())) return c.reply('Usage: .daysto 2025-12-25'); const days = Math.ceil((d - new Date()) / 86400000); c.reply(`📅 *Countdown*\n\nDate: ${d.toDateString()}\n${days > 0 ? `${days} days remaining` : days === 0 ? 'That\'s today!' : `${Math.abs(days)} days ago`}`); }},
    { commands: ['clock', 'time'], description: 'Current time', permission: 'public', run: async (s, m, a, c) => { const tz = a[0] || 'Africa/Nairobi'; try { c.reply(`🕐 ${new Date().toLocaleString('en-US', {timeZone:tz, hour:'2-digit', minute:'2-digit', second:'2-digit', hour12:true, weekday:'short', month:'short', day:'numeric'})}`); } catch { c.reply(`🕐 ${new Date().toLocaleString()}`); } }},
    { commands: ['speedtest', 'speed'], description: 'Bot speed test', permission: 'public', run: async (s, m, a, c) => { const start = Date.now(); await c.reply('Testing speed...'); const ping = Date.now() - start; const mem = process.memoryUsage(); c.reply(`⚡ *Speed Test*\n\nResponse: ${ping}ms\nRAM: ${(mem.heapUsed/1e6).toFixed(1)}MB / ${(mem.heapTotal/1e6).toFixed(1)}MB\nUptime: ${Math.floor(process.uptime()/60)}m`); }},
];
