#============================================================================================#   
#                                      GIFTED－MD                                             # 
#                                                                                             # 
#                                   VERSION ：2．5．0                                          # 
#                                                                                             # 
#                                                                                             # 
#           ██████╗ ██╗███████╗████████╗███████╗██████╗     ███╗   ███╗██████╗                # 
#          ██╔════╝ ██║██╔════╝╚══██╔══╝██╔════╝██╔══██╗    ████╗ ████║██╔══██╗               # 
#          ██║  ███╗██║█████╗     ██║   █████╗  ██║  ██║    ██╔████╔██║██║  ██║               # 
#          ██║   ██║██║██╔══╝     ██║   ██╔══╝  ██║  ██║    ██║╚██╔╝██║██║  ██║               # 
#          ╚██████╔╝██║██║        ██║   ███████╗██████╔╝    ██║ ╚═╝ ██║██████╔╝               # 
#           ╚═════╝ ╚═╝╚═╝        ╚═╝   ╚══════╝╚═════╝     ╚═╝     ╚═╝╚═════╝                # 
#                                                                                             # 
#                                                                                             # 
#                                                                                             # 
#                                                                                             # 
#=============================================================================================# 
#                                                                 
#    * @project_name : Gifted-Md
#    * @author : @GiftedTech
#    * @youtube : https://www.youtube.com/@giftedtechnexus
#    * @description : Gifted-Md ,A Multi-functional whatsapp bot md.
#    * @version 2.5.0
# 
# Don't change this [ /GiftedTech/ ] name!
# Change from below link, else bot not works!

 

FROM quay.io/SilvaTechB/SilvaGifted
RUN git clone https://github.com/SilvaTechB/SilvaGifted /root/SilvaGifted
WORKDIR /root/SilvaGifted/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
